### ISSUE TITLE
Fantastic! Collaboration

### ISSUE THREAD

**Issue by Noitidart** [schomery/reverse-image-search#1]
Thanks very much for your reply to my review: https://addons.mozilla.org/en-US/firefox/addon/capture-reverse-image-search/reviews/748872/

This addon really should have more users.

Is this a purely firefox addon?

I would love to collaborate to bring in support for google images, and also right click + search ability.

**Comment by schomery** [comment]
Hi @Noitidart 

Sorry for very late reply! I haven't got the notification in my inbox. No the addon is also available for Chrome and Opera as well. Basically there are three wrappers [for platform based operations](https://github.com/schomery/reverse-image-search/tree/master/src.safariextension/lib). You can go forward and apply your changes to the Firefox version. I'll take care of making them compatible for Chrome and Opera.

Let me know if you need more info
