### ISSUE TITLE
Stopped passing info to Tineye

### ISSUE THREAD

**Issue by spmtrap96** [schomery/reverse-image-search#2]
Your add-on used to work Great!! - But now it's stopped sending the capture info to Tineye (in Firefox and Chrome on Win7 & Win10 PC's) - When I right click and select something to grab, I get the capturing message, then it opens Tineye at it's main page with no search info, just the default tineye page.

**Comment by schomery** [comment]
Thanks for the report. I just submitted a new version that fixes this issue.

**Comment by spmtrap96** [comment]
GREAT NEWS!! - Where/When can we download it?

**Comment by schomery** [comment]
Chrome version is live. Firefox version is still in the approval queue!
