### ISSUE TITLE
Google Images search

### ISSUE THREAD

**Issue by Faberman** [schomery/reverse-image-search#3]
Hello.
I really like the capture feature, but what this extension really lacks is searching on Google Images. Could you add it? I've checked the code and it will be fairly easy to do. I suggest this simple snippet for default 'Search by URL' option:

```
else if (info.menuItemId === 'search-link') {
    chrome.tabs.create({
        url: 'https://www.google.com/searchbyimage?image_url=' + encodeURIComponent(info.srcUrl),
        active: true
    });
}
```

And there's no need in `let formData = new window.FormData();` block.

The capture option only requires another POST URL: `https://www.google.com/searchbyimage/upload` and replacing `image` with `encoded_image` in `formData.append('image', blob, 'screenshot.png');`.

And finally combine these two search engines in a submenu like this:

```
Reverse Image Search =>
                       Google Images
                       TinEye
```

P. S. Talking about Firefox version, but there are no differences now, because of Web Extensions.

**Comment by schomery** [comment]
Google Image support is added; Please give it a try and let me know how it performs

https://github.com/schomery/reverse-image-search/tree/master/webextension

**Comment by Faberman** [comment]
Thanks for your quick reply. Unfortunately, capture doesn't work. I guess it's because inject.css and inject.js are empty.

By the way, TinEye search by url code can also be replaced with:
```
    if (tineye) {
      chrome.tabs.create({
        url: 'https://www.tineye.com/search?url=' + encodeURIComponent(info.srcUrl)
      });
    }
```

Also how about renaming context menu entries from Image URL (Google Image)/Image URL (Tineye) to Google Images (image url)/TinEye (image url)? The same with Capture option. It's just easier to distinguish search engines this way.

**Comment by schomery** [comment]
> I guess it's because inject.css and inject.js are empty.

Right! I am using links from Easy-Screenshot extension. Try this one
[beta.zip](https://github.com/schomery/reverse-image-search/files/1010847/beta.zip)

> By the way, TinEye search by url code can also be replaced wit

We used to do it this way, but apparently this method is not reliable. TinEye removed it once and it is back again!

**Comment by Faberman** [comment]
Works great, thanks!

>We used to do it this way, but apparently this method is not reliable. TinEye removed it once and it is back again!

I see. Didn't know about it.

**Comment by schomery** [comment]
Perfect! New version is submitted to AMO for review. Thanks for the suggestion!
