### ISSUE TITLE
Capture google "Failed! [object ProgressEvent]" due to changes in Chrome regarding CORS handling

### ISSUE THREAD

**Issue by lbreuss** [schomery/reverse-image-search#6]
The Capture and upload to google fails. Looking at the Extension --> Error, Developer console, the underlying reason shows up to be a CORS policy problem. 

```Access to XMLHttpRequest at 'https://www.google.com/searchbyimage/upload' from origin 'chrome-extension://clijmpalajoikbhdhgmpanldenogllaj' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

**Comment by lbreuss** [comment]
Fixing it while migrating to Manifest V3 (probably) requires
- adding to the manifest a "host_permissions" for "https://*.google.com/"
- which requires to [migrate the manifest to v3](https://developer.chrome.com/docs/extensions/mv3/mv3-migration-checklist/), [SO question v2 ot v3](https://stackoverflow.com/questions/63308160/how-to-migrate-manifest-version-2-to-v3-for-chrome-extension), [mv3 migration](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/)
- which requires to migrate the background page stuff to [service worker](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/)

I failed at declaring the service_worker, or doing any necessary code changes... This is how far I got: https://github.com/lbreuss/reverse-image-search/tree/manifest_v3
 (I'm a frontend layman, pls forgive any imprecise wording.)

**Comment by lbreuss** [comment]
I fixed it on master branch for manifest v2, pull request https://github.com/schomery/reverse-image-search/pull/7

**Comment by schomery** [comment]
Perfect! Seems like we can narrow down the permission to `www.google.com/searchbyimage/upload` though. For TinEye there is no need for the permission since the server fetches the image

**Comment by lbreuss** [comment]
> Perfect! Seems like we can narrow down the permission to `www.google.com/searchbyimage/upload` though. For TinEye there is no need for the permission since the server fetches the image

You're right, it's just the upload url... thanks for fixing it.
